apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orikerbis/gitops
    targetRevision: main
    path: gitops-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true