apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
spec:
  project: default
  sources:
    - path: helm-webapp
      repoURL: https://github.com/orikerbis/argo-examples
      targetRevision: master
      helm:
        valuesFiles:
          - $values/gitops-chart/values.yaml
    - repoURL: https://github.com/orikerbis/gitops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true